# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WarrantyGuard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WarrantyGuard

   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'Firebase/Storage'
   pod 'SDWebImage', '~> 5.0'

end
